services:
  - type: web
    name: logistima-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RUN_MIGRATIONS
        value: true
      - key: SEED_DB
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: logistima-db
          property: connectionString

databases:
  - name: logistima-db
    databaseName: logistima_prod
    user: logistima_user
    plan: free
    region: frankfurt